### ISSUE TITLE
+ and - should warn (or balk?) if dimensions of operands are similar but not identical.

### ISSUE THREAD

**Issue by triangle-man** [decc/siunits#1]
In principle 5 N m + 6 N m should fail, since the first N m might be energy, and the second N m might be torque. Not sure how to play this one.

**Comment by tamc** [comment]
I'd suggest that:
1 unless it knows otherwise\* it should assume the two are compatible, otherwise it will just be annoying for the user who in most cases will already know they are compatible
2 have an optional warning that the units are not specific enough. Optional because you won't want to read the warning every time you do the analysis, just when you set it up. 

Tom
- if it had access to the variable names for data passed to it, or table column names, then it could try and spot their incompatibility !

**Comment by triangle-man** [comment]
I think an optional warning is right. In R, warnings are turned off if there are more than a few all the same.
- So ... I still don't really understand dimensions. Physically, you're not even allowed to suppose that a length may be added to any other length, since they could in principle refer to different kinds of quantity. One might be position, say, and the other wavelength. On the other hand, it's not _crazy_ to add two lengths in the same way that it is crazy to add an energy and a torque. 

Broadly speaking, I think that the two quantities you're attempting to add must live in the same vector space. That is, you can add "(N m)_[energy]" and "(kg m^2 s^-2)_[energy]" because they are both quantities valued in "[energy]". (The system accepts this notation, by the way.) But adding even "N m" to "N m" should emit at least a warning, because these are not necessarily the same vector space. And adding "(N m)_[torque]" to "(N m)_[energy]" should be outright rejected.
